[build]
  command = "npm run build"
  publish = "build-output"

 [[redirects]]
  from = "https://christinetrac.dev"
  to = "https://www.christinetrac.dev"
 [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
